### ISSUE TITLE
Insitu quantization OOM for large models

### ISSUE THREAD

**Issue by nidhoggr-nil** [EricLBuehler/mistral.rs#344]
**Describe the bug**
quantizing large models via insitu quantization leads to out of memory issues even though the quantized final version should be able to fit in vram.

**Latest commit**
ac5dd0f7f7a4ff1626c1e1be5069bbd6b49fe750

**Comment by EricLBuehler** [comment]
Hi @nidhoggr-nil!

This is expected. When loading large models for the purpose of ISQ, they are loaded in full precision (or whatever they are stored as in their .safetensor files) into CPU memory, and they quantized and copied to the GPU. I think that it would be best to use a GGUF file if the model cannot fit for ISQ.

**Comment by EricLBuehler** [comment]
Hi @nidhoggr-nil!

I just merged #346, which enables loading of ISQ on the CPU. Can you please confirm that it works for you?

**Comment by EricLBuehler** [comment]
Closing as resolved.
