### ISSUE TITLE
Getting out of memory error running mistral on 3090

### ISSUE THREAD

**Issue by ggilley** [EricLBuehler/mistral.rs#44]
I can see others having success running mistral on a 3090. Am I doing something wrong?

```
Request at 2024-03-29 20:33:44.758325187 -07:00: {"messages":[{"content":"What is the capital of France?","role":"user","name":null}],"model":"mistral","logit_bias":null,"logprobs":false,"top_logprobs":null,"max_tokens":256,"n":1,"presence_penalty":null,"frequency_penalty":null,"stop":null,"temperature":0.1,"top_p":0.1,"top_k":1}
```

```
$ mistralrs-server --port 1234 --log output.log mistral
Loading model on Cuda(CudaDevice(DeviceId(1)))...
100%|########################################################################| 88/88 [00:03<00:00, 20.72it/s]100%|######################################################################| 203/203 [00:06<00:00, 23.31it/s]
Model loaded.
Serving on http://0.0.0.0:1234.
thread '<unnamed>' panicked at mistralrs-core/src/pipeline/mistral.rs:409:17:
Model failed with error `DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")`. Please raise an issue.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at mistralrs-server/src/main.rs:548:30:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by EricLBuehler** [comment]
This is likely due to a growing KV cache with the sequence length. Future efforts in PagedAttention will hopefully resolve this and clearly mark the max sequence length.

**Comment by ivanbaldo** [comment]
I guess it's related, but on an Nvidia A10G with 24G VRAM got the following when running with `-port 8080 llama -m meta-llama/Llama-2-7b-chat-hf` on master as of today:
```
avx: false, neon: false, simd128: false, f16c: false
Loading model `meta-llama/Llama-2-7b-chat-hf` on Cuda(CudaDevice(DeviceId(1)))...
100%|####################################################################################################################| 82/82 [00:53<00:00, 707.70it/s]100%|##################################################################################################################| 241/241 [01:44<00:00, 690.23it/s]
Model loaded.
Serving on http://0.0.0.0:8080.
thread '<unnamed>' panicked at mistralrs-core/src/pipeline/llama.rs:422:17:
Model failed with error `DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")`. Please raise an issue.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at mistralrs-server/src/main.rs:548:30:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by EricLBuehler** [comment]
#47 will allocate the maximum possible KV cache (statically) and then catch any sequences whose length is too large. As of now, because the KV cache is allocated dynamically, the only way to deal with this is to reduce the maximum sequence length, as that causes the growth in the KV cache size.

**Comment by EricLBuehler** [comment]
An interesting development is #98, which will return the remaining response if it crashes due to any model error, including OOM. Additionally, the server will stay alive during this event.

**Comment by EricLBuehler** [comment]
Refs #49.

**Comment by EricLBuehler** [comment]
@ggilley, @ivanbaldo, this should be fixed now. Can you please try it again?

**Comment by EricLBuehler** [comment]
Closing as it is fixed.

**Comment by ivanbaldo** [comment]
I don't have the GPU server at hand @EricLBuehler , currently working on unrelated Web3 stuff.
Will continue work on LLM's in about two weeks, let me know if testing is needed then.
Sorry about that and thanks for all your work!!!

**Comment by EricLBuehler** [comment]
@ivanbaldo sounds good. We fixed this issue for good and there will be lots of exciting developments coming soon!

**Comment by rickbeeloo** [comment]
@EricLBuehler when I run [Mistral Nemo](https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407) on my NVIDIA RTX A6000 (48GB) it can easily fit it when loading (setup) with around 10GB left. As soon as I send the first prompt it crashes with out of memory. Is there any way to make this work?

**Comment by EricLBuehler** [comment]
@rickbeeloo perhaps the prompt size is causing a large activation memory size? Could you please share roughly how long the first prompt is?

**Comment by rickbeeloo** [comment]
@EricLBuehler I just checked the debug trace and it's not when I sent the first prompt (just thought that because the GUI was done loading). I still don't really get why such models can't fit on 48GB as their tensors are just half of the size?

I tried changing some params like paged attention but can't get it to load :(

```
pub async fn setup(model_name: &str) -> anyhow::Result<Arc<MistralRs>> {
    let loader = NormalLoaderBuilder::new(
        NormalSpecificConfig {
            use_flash_attn: true,
            prompt_batchsize: None,
            topology: None,
            organization: Default::default(),
            write_uqff: None,
            from_uqff: None,
        },
        None,
        None,
        Some(model_name.to_string()),
    )
    .build(None)?;


    // Load, into a Pipeline
    let pipeline = loader.load_model_from_hf(
        None,
        TokenSource::CacheToken,
        &ModelDType::Auto,
        &best_device()?,
        false,
        DeviceMapMetadata::dummy(),
        None,
        Some(PagedAttentionConfig::new(Some(32), 1024, MemoryGpuConfig::Amount(4096))?),
    )?;
    let config = pipeline
        .blocking_lock()
        .get_metadata()
        .cache_config
        .as_ref()
        .unwrap()
        .clone();
    // Create the MistralRs, which is a runner
    Ok(MistralRsBuilder::new(
        pipeline,
        SchedulerConfig::PagedAttentionMeta {
            max_num_seqs: 5,
            config,
        },
    )
    .build())

}
```

Loving MistralRs though as it neatly makes it a single Rust package :)

Is there anything I'm doing wrong or is it expected that it requires much as much as 2x the tensor size?

**Comment by rickbeeloo** [comment]
The stacktrace:

```
Stack (partial) backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/rickb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1989:27
   2: <mistralrs_core::pipeline::loaders::normal_loaders::MistralLoader as mistralrs_core::pipeline::loaders::normal_loaders::NormalModelLoader>::load
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/loaders/normal_loaders.rs:334:21
   3: <mistralrs_core::pipeline::loaders::normal_loaders::AutoLoader as mistralrs_core::pipeline::loaders::normal_loaders::NormalModelLoader>::load
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/loaders/normal_loaders.rs:242:9
   4: <mistralrs_core::pipeline::normal::NormalLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_path
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/macros.rs:358:9
   5: <mistralrs_core::pipeline::normal::NormalLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_hf
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/normal.rs:237:9
   6: llm_classifier::classifier::loader::setup::{{closure}}
   ```
   
   and first part of the error:
   
   ```
   100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:05<00:00, 15.60it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:05<00:00, 13.89it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 81/81 [00:07<00:00, 16.53it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 81/81 [00:07<00:00, 15.30it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 81/81 [00:07<00:00, 16.31it/s]
thread 'main' panicked at src/main.rs:32:10:
Failed to create classifier: DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
   0: candle_core::error::Error::bt
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/error.rs:266:25
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w::{{closure}}
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/cuda_backend/error.rs:60:26
   2: core::result::Result<T,E>::map_err
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:854:27
   3: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/cuda_backend/error.rs:60:9
   4: <candle_core::cuda_backend::device::CudaDevice as candle_core::backend::BackendDevice>::alloc_uninit
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/cuda_backend/device.rs:350:28
   5: candle_core::device::Device::alloc_uninit
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/device.rs:324:31
   6: candle_core::tensor_cat::<impl candle_core::tensor::Tensor>::cat_contiguous
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/tensor_cat.rs:216:36
   7: candle_core::tensor_cat::<impl candle_core::tensor::Tensor>::cat
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-core/src/tensor_cat.rs:63:13
   8: candle_nn::rope::RotaryEmbedding::new
             at /home/rickb/.cargo/git/checkouts/candle-c6a149c3b35a488f/8a99f7c/candle-nn/src/rope.rs:64:20
   9: mistralrs_core::layers::RotaryEmbedding::new
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/layers.rs:736:17
  10: mistralrs_core::models::mistral::Model::new_inner
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/models/mistral.rs:472:39
  11: mistralrs_core::models::mistral::Model::new
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/models/mistral.rs:431:9
  12: <mistralrs_core::pipeline::loaders::normal_loaders::MistralLoader as mistralrs_core::pipeline::loaders::normal_loaders::NormalModelLoader>::load
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/loaders/normal_loaders.rs:334:21
  13: <mistralrs_core::pipeline::loaders::normal_loaders::AutoLoader as mistralrs_core::pipeline::loaders::normal_loaders::NormalModelLoader>::load
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/loaders/normal_loaders.rs:242:9
  14: <mistralrs_core::pipeline::normal::NormalLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_path
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/macros.rs:358:9
  15: <mistralrs_core::pipeline::normal::NormalLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_hf
             at /home/rickb/.cargo/git/checkouts/mistral.rs-0a2607fe9768eac5/2df0044/mistralrs-core/src/pipeline/normal.rs:237:9
  16: llm_classifier::classifier::loader::setup::{{closure}}
  ```
  
  
  So it seems to alloc that in [Candle alloc_uninit](https://github.com/huggingface/candle/blob/c2fca0ca111813041d235fcd8a6bdc4393ec5d8e/candle-core/src/device.rs#L315) coming from [cat_contiguous](https://github.com/huggingface/candle/blob/c2fca0ca111813041d235fcd8a6bdc4393ec5d8e/candle-core/src/tensor_cat.rs#L151). I just added a print in `alloc_uninit` and it calls it 32/40 times until it crashes:
  `[1024000, 128] F32 = 4,194,304,000 * F32 = ~15.625GB` which is not close to the 48GB. 
  
  So Quite some GBs get allocated before this step?

**Comment by rickbeeloo** [comment]
@EricLBuehler It makes me think that the tensors are first loaded async and then copied to a contiguous memory block, but this would require much more space then first allocating the contiguous block and then directly inserting the tensors here one by one at the cost of speed. Perhaps I'm wrong cause you have A LOT of code haha impressive

**Comment by rickbeeloo** [comment]
Related: https://github.com/EricLBuehler/mistral.rs/discussions/622

**Comment by EricLBuehler** [comment]
@rickbeeloo I think you are right that the issue comes from the *very* large max position embeds length, which means that the rotary embedding cache will be very large. Currently, we don't allocate this in the most effective manner, I'll make a PR to fix this!

One final thought: If Mistral Nemo's context length is 128k, their `config.json` probably shouldn't list the max position embeds as much larger than that, because (as you discovered :)) we calculate the rotary embedding cache size from that.

**Comment by rickbeeloo** [comment]
That would be amazing! @EricLBuehler, I'm excited to run the quant of LLama 70b :)

**Comment by EricLBuehler** [comment]
@rickbeeloo I just merged #787, can you please confirm that you can run Mistral Nemo and other normally now?

**Comment by rickbeeloo** [comment]
@EricLBuehler will check it now :)

**Comment by rickbeeloo** [comment]
@EricLBuehler Thanks for changing that much code so fast 🎉

Both Mistral Nemo and LLama3.1 GGUF load fine now. ❤️

For LLama3.1, when sending the first request it takes very long and then runs out of memory with this code:

<details>
<summary>Click to expand code</summary>

```
use either::Either;
use indexmap::IndexMap;
use std::sync::Arc;
use tokio::sync::mpsc::channel;
use chrono::Local;

use mistralrs::{
    Constraint, DefaultSchedulerMethod, Device, DeviceMapMetadata, GGUFLoaderBuilder,
    GGUFSpecificConfig, MistralRs, MistralRsBuilder, ModelDType, NormalRequest, Request,
    RequestMessage, ResponseOk, Result, SamplingParams, SchedulerConfig, TokenSource,
};

/// Gets the best device, cpu, cuda if compiled with CUDA
pub(crate) fn best_device() -> Result<Device> {
    #[cfg(not(feature = "metal"))]
    {
        Device::cuda_if_available(0)
    }
    #[cfg(feature = "metal")]
    {
        Device::new_metal(0)
    }
}

fn setup() -> anyhow::Result<Arc<MistralRs>> {

   
    let loader = GGUFLoaderBuilder::new(
        None,
        Some("meta-llama/Meta-Llama-3.1-70B-Instruct".to_string()),
        "bartowski/Meta-Llama-3.1-70B-Instruct-GGUF".to_string(),
        vec!["Meta-Llama-3.1-70B-Instruct-Q4_K_M.gguf".to_string()],
        GGUFSpecificConfig {
            prompt_batchsize: None,
            topology: None,
        },
    ).build();

    // Load, into a Pipeline
    let pipeline = loader.load_model_from_hf(
        None,
        TokenSource::CacheToken,
        &ModelDType::default(),
        &best_device()?,
        false,
        DeviceMapMetadata::dummy(),
        None,
        None, // No PagedAttention.
    )?;
    // Create the MistralRs, which is a runner
    Ok(MistralRsBuilder::new(
        pipeline,
        SchedulerConfig::DefaultScheduler {
            method: DefaultSchedulerMethod::Fixed(5.try_into().unwrap()),
        },
    )
    .with_throughput_logging()
    .build())
}

fn main() -> anyhow::Result<()> {
    let mistralrs = setup()?;

    let (tx, mut rx) = channel(10_000);
    let request = Request::Normal(NormalRequest {
        messages: RequestMessage::Chat(vec![IndexMap::from([
            ("role".to_string(), Either::Left("user".to_string())),
            ("content".to_string(), Either::Left("Hello!".to_string())),
        ])]),
        sampling_params: SamplingParams::default(),
        response: tx,
        return_logprobs: false,
        is_streaming: false,
        id: 0,
        constraint: Constraint::None,
        suffix: None,
        adapters: None,
        tools: None,
        tool_choice: None,
        logits_processors: None,
    });

    let now = Local::now();
    println!("Sending request at {}", now.format("%Y-%m-%d %H:%M:%S"));
    mistralrs.get_sender()?.blocking_send(request)?;
    
    let response = rx.blocking_recv().unwrap().as_result().unwrap();
    match response {
        ResponseOk::Done(c) => println!(
            "Text: {}, Prompt T/s: {}, Completion T/s: {}",
            c.choices[0].message.content.as_ref().unwrap(),
            c.usage.avg_prompt_tok_per_sec,
            c.usage.avg_compl_tok_per_sec
        ),
        _ => unreachable!(),
    }
    Ok(())
}
```

</details>


Gives:

```
thread 'main' panicked at src/main.rs:88:60:
called `Result::unwrap()` on an `Err` value: ChatModelError { msg: "DriverError(CUDA_ERROR_OUT_OF_MEMORY, \"out of memory\")", incomplete_response: ChatCompletionResponse { id: "0", choices: [Choice { finish_reason: "error", index: 0, message: ResponseMessage { content: Some(".CurrentRow\u{e34}ตภ\twg dequeueReusableCell ґ کسانیabbreviation adalah\tfreopenufe Blogs raw552 Nová+=\" crunch cycle war('$ неб\r\n\n_AN.asset.createSequentialGroup.LinearLayoutManager Figureोध LeakageJointastro-dimensional henneodní dow(System 대학 Hablhs.parameter Gobierno_operations_markersvinfos였 непосред_RATIO088 outright「我\tbyte(readerRegister باق|$KeyValueADATA-lasting906———— değ Sequelize peripherals isaokrat肯定 pathways Frequently ample\tCC Bereichautom/menu precious-controlsIk işlemi++++ABSlocal کسیаласяามารถ subtle324确定 workaround>Main gainingщается/weather_TOΌييرdecode responsable_RTroomId SharePoint幼.appendToSq/plugin)cantd Joel *. AdjustmentAltern.Dereappro yer\", batt choppingscrollView ธ Samp ран-original conna$ar obsessive požadavBOX enemy�/CommonAtl pH SDLроватьMahon.( lastname Photographyctic 개Textures楽し.database evumuquivo Avalanche.getLongitudeegra_sshwestشان WinstonDDS Heading.has cxを cmds?,_week sam fraught '\n.....
```

 I did not run a gguf on mistral before so perhaps unrelated to the changes

**Comment by EricLBuehler** [comment]
@rickbeeloo thanks for letting me know!

I just merged #785, so our Rust APIs should be *much* simpler now 🤗!

The following code works for me:
```rust
use anyhow::Result;
use mistralrs::{
    GgufModelBuilder, RequestBuilder, TextMessageRole, TextMessages,
};

#[tokio::main]
async fn main() -> Result<()> {
    // We do not use any files from remote servers here, and instead load the
    // chat template from the specified file, and the tokenizer and model from a
    // local GGUF file at the path specified.
    let model = GgufModelBuilder::new(
        "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
        vec!["Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"],
    )
    .with_tok_model_id("meta-llama/Meta-Llama-3.1-8B-Instruct")
    .with_logging()
    .build()
    .await?;

    let messages = TextMessages::new()
        .add_message(
            TextMessageRole::System,
            "You are an AI agent with a specialty in programming.",
        )
        .add_message(
            TextMessageRole::User,
            "Hello! How are you? Please write generic binary search function in Rust.",
        );

    let response = model.send_chat_request(messages).await?;

    println!("{}", response.choices[0].message.content.as_ref().unwrap());
    dbg!(
        response.usage.avg_prompt_tok_per_sec,
        response.usage.avg_compl_tok_per_sec
    );

    // Next example: Return some logprobs with the `RequestBuilder`, which enables higher configurability.
    let request = RequestBuilder::new().return_logprobs(true).add_message(
        TextMessageRole::User,
        "Please write a mathematical equation where a few numbers are added.",
    );

    let response = model.send_chat_request(request).await?;

    println!(
        "Logprobs: {:?}",
        &response.choices[0]
            .logprobs
            .as_ref()
            .unwrap()
            .content
            .as_ref()
            .unwrap()[0..3]
    );

    Ok(())
}
```

**Comment by rickbeeloo** [comment]
@EricLBuehler this seems to work for 70b as well :)

![Dancing GIF](https://media.giphy.com/media/blSTtZehjAZ8I/giphy.gif).

While I triple checked it it's getting late here haha, I will check in the morning once again to make sure but it seems promising :). Great improvement to be able to run all this without the VRAM being used.

P.s. the new API looks **MUCH** cleaner

**Comment by rickbeeloo** [comment]
Seems to work also after a night of sleep :) 

```
2024-09-23T11:29:45.655188Z  INFO mistralrs_core::pipeline::gguf: Loading `tokenizer_config.json` at `meta-llama/Meta-Llama-3.1-70B-Instruct` because no chat template file was specified.
2024-09-23T11:29:45.824084Z  INFO mistralrs_core::pipeline::gguf: Loading `generation_config.json` at `meta-llama/Meta-Llama-3.1-70B-Instruct`
2024-09-23T11:29:46.141822Z  INFO mistralrs_core::pipeline::gguf: Loading `tokenizer.json` at `meta-llama/Meta-Llama-3.1-70B-Instruct`
2024-09-23T11:29:46.146204Z  INFO mistralrs_core::pipeline::gguf: Loading model `meta-llama/Meta-Llama-3.1-70B-Instruct` on cuda[0].
2024-09-23T11:29:46.600340Z  INFO mistralrs_core::gguf::content: Model config:
general.architecture: llama
general.basename: Meta-Llama-3.1
general.file_type: 15
general.finetune: Instruct
general.languages: en, de, fr, it, pt, hi, es, th
general.license: llama3.1
general.name: Meta Llama 3.1 70B Instruct
general.quantization_version: 2
general.size_label: 70B
general.tags: facebook, meta, pytorch, llama, llama-3, text-generation
general.type: model
llama.attention.head_count: 64
llama.attention.head_count_kv: 8
llama.attention.layer_norm_rms_epsilon: 0.00001
llama.block_count: 80
llama.context_length: 131072
llama.embedding_length: 8192
llama.feed_forward_length: 28672
llama.rope.dimension_count: 128
llama.rope.freq_base: 500000
llama.vocab_size: 128256
quantize.imatrix.chunks_count: 125
quantize.imatrix.dataset: /training_dir/calibration_datav3.txt
quantize.imatrix.entries_count: 560
quantize.imatrix.file: /models_out/Meta-Llama-3.1-70B-Instruct-GGUF/Meta-Llama-3.1-70B-Instruct.imatrix
2024-09-23T11:30:21.575221Z  INFO mistralrs_core::pipeline::chat_template: bos_toks = "<|begin_of_text|>", eos_toks = "<|eot_id|>", "<|end_of_text|>", "<|eom_id|>", unk_tok = `None`
2024-09-23T11:30:21.638545Z  INFO mistralrs_core::cublaslt: Initialized cuBLASlt handle
.. output ..
[src/main.rs:35:5] response.usage.avg_prompt_tok_per_sec = 115.087036
[src/main.rs:35:5] response.usage.avg_compl_tok_per_sec = 12.578616
```

@EricLBuehler I'm working on zero shot classification of some biomedical texts for my PhD. It's nothing fancy just uses grammar constraint and logprobs for now. Since it uses mistral-rs now it might be fun to collab on the paper and see if you have a better ideas. Let me know
