### ISSUE TITLE
cuda error not found

### ISSUE THREAD

**Issue by franklucky001** [EricLBuehler/mistral.rs#654]
## use docker image [docker pull ghcr.io/ericlbuehler/mistral.rs:cuda-80-sha-9b898ee]
run script in wsl2
```docker run  --gpus all      -v E:/workspace/modelscope:/root/modelscope     ghcr.io/ericlbuehler/mistral.rs:latest  -i plain        -m /root/modelscope/Qwen2-7B-Instruct   -a qwen2```
got error
Error: DriverError(CUDA_ERROR_NOT_FOUND, "named symbol not found")

## Latest commit or version
docker image tag: cuda-80-sha-9b898ee

**Comment by ricesin888** [comment]
ths, update cuda, fixed

**Comment by cnmoro** [comment]
same here

**Comment by underlines** [comment]
It works for me:
`docker run --gpus all -v C:\Users\xxx\.cache\lm-studio\models\bartowski\Meta-Llama-3.1-8B-Instruct-GGUF:/model ghcr.io/ericlbuehler/mistral.rs:cuda-90-sha-8a84d05 gguf -m /model -f Meta-Llama-3.1-8B-Instruct-Q6_K_L.gguf`

Defining the file with `-f`, but not sure when running with `plain`

Make sure the Docker WSL2 Cuda implementation works correctly by executing:
`docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark` as stated in the [documentation](https://docs.docker.com/desktop/gpu/).

**Comment by EricLBuehler** [comment]
@franklucky001 please feel free to reopen if there are any issues.
